chore: YAML pls

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -277,9 +277,17 @@ create-release:
     # TODO: Verify whether release actually needs to happen; get GitHub App Token;
     # create draft release; upload artifacts
     - RELEASE_VERSION=$(grep -E '^project\(ddsdkcpp VERSION ([0-9]+\.[0-9]+\.[0-9]+[^ ]*)' CMakeLists.txt | cut -d' ' -f3)
-    - "[ -n \"$RELEASE_VERSION\" ] || { echo \"ERROR: Failed to parse version from CMakeLists.txt\" >&2; exit 1 }"
+    - |
+      if [ "$RELEASE_VERSION" == "" ]; then
+        echo "ERROR: Failed to parse version from CMakeLists.txt" >&2
+        exit 1
+      fi
     - ARCHIVE_FILES=$(find build -maxdepth 1 -type f \( -name 'ddsdkcpp-*.tar.gz' -o -name 'ddsdkcpp-*.zip' \))
-    - "[ -n \"$ARCHIVE_FILES\" ] || { echo \"ERROR: No archive files found in previous jobs' artifacts\" >&2; exit 1 }"
+    - |
+      if [ "$ARCHIVE_FILES" == "" ]; then
+        echo "ERROR: No archive files found in previous jobs' artifacts" >&2
+        exit 1
+      fi
     - |
       echo "Preparing release of dd-sdk-cpp $RELEASE_VERSION."
       echo "Artifacts found:"
